### ISSUE TITLE
One reload per file change causes issues with large directories.

### ISSUE THREAD

**Issue by miltonwaddams** [mucsi96/gulp-jasmine-livereload-task#1]
Hello there.

We're having an issue where there's one reload per file changed in the watched directory.  If too many files change and too many reloads happen, this will leave us with a blank white screen.  This happens about 80% of the time in Chrome.  Manually refreshing does fix this but it sort of defeats the purpose of live reload.

Is there any config option that can add a delay in the watched directory?

Thank you so much!

**Comment by mucsi96** [comment]
Thanks for feedback! I changed the watch package to [`gulp-debounced-watch`](https://www.npmjs.com/package/gulp-debounced-watch). Now even if many files change only one reload should happen.

**Comment by miltonwaddams** [comment]
Thank you for the quick fix!
