### ISSUE TITLE
TypeError: test.addMatchers is not a function

### ISSUE THREAD

**Issue by stiltet** [mucsi96/gulp-jasmine-livereload-task#6]
Hi,

First of all thanks for a geat module. :)

I'm having troubles using your module with JSHint. See sourcecode bellow and result in attached image.

![screenshot](https://cloud.githubusercontent.com/assets/4058653/19416832/0afbf24a-939b-11e6-9d05-72a177723e5e.png)

`var gulp = require('gulp'),
    jasmineLiveReload = require('gulp-jasmine-livereload-task');

var scriptsInput = 'www/assets/js/**/*.js',
    scriptTestsInput = 'www/assets/js/**/*_spec.js';

gulp.task('jasmine', jasmineLiveReload({
    files: [scriptsInput, scriptTestsInput],
    jshint: {
        files: [scriptsInput, scriptTestsInput],
        options: {
            curly: true,
            white: true,
            indent: 2
        }
    },
    watch: {
        options: {
            debounceTimeout: 1000,
            debounceImmediate: true
        }
    },
    host: 'localhost',
    port: 8888,
}));

gulp.task('watch', function () {
    gulp.watch(scriptsInput, ['scripts', 'jasmine']);
});

gulp.task('default', ['clean'], function () {
    gulp.start('styles');
    gulp.start('jasmine');
    gulp.start('scripts');
    gulp.start('watch');
});

gulp.task('build', ['default']);`

**Comment by atikenny** [comment]
Hi,

Thanks for the report, you are absolutely right about the issue.
The fix is on it's way in 0.10.1, you can use the 0.9.0 version meanwhile, it should work with your example.

Thanks

**Comment by mucsi96** [comment]
Hi,

The fix is released in `0.10.1`. Thanks @atikenny for contribution! 😉

**Comment by stiltet** [comment]
Thanks! 👏🏼
mån 24 okt. 2016 kl. 19:19 skrev Igor Muchychka notifications@github.com:
