### ISSUE TITLE
Fix peer dependency support

### ISSUE THREAD

**Issue by glebec** [mucsi96/gulp-jasmine-livereload-task#9]
https://github.com/mucsi96/gulp-jasmine-livereload-task/blob/master/index.js#L19 tries to use a `SpecRunner.html` file from the npm package `jasmine` (on GitHub as [jasmine-npm](https://github.com/jasmine/jasmine-npm)), but `jasmine` does not (and has not, at least going back through Jasmine 2.0) include such a file. The _standalone releases_ do have such a runner file.

This means that `gulp-jasmine-livereload-task` will never succeed in finding a peer version of the runner, which means for now we are stuck with the embedded 2.2 or lower. Or one could commit a standalone release inside one's project, but not use an npm dependency with SEMVER.

The ideal would be if `jasmine` or `jasmine-core` (on GitHub as [jasmine](https://github.com/jasmine/jasmine)) either include the spec runner, in which case this project can be updated to use the correct path. I haven't thoroughly checked either package yet.

---

Follow up: the standalone releases, which include a spec runner, are built at https://github.com/jasmine/jasmine/blob/8624a52ee0b6f13b3b608ea6417ccc02257c5412/grunt/tasks/build_standalone.js#L5.

---

Second follow-up: one way forward would be to simply use `jasmine-core` with an embedded SpecRunner.html. I don't believe the runner HTML has really changed in any way for a while. Of course that may break in future versions, but hopefully `jasmine-core` would use proper SEMVER major version changes to indicate that if so.

**Comment by glebec** [comment]
The plot thickens. It looks like @mucsi96 actually worked on this in https://github.com/mucsi96/gulp-jasmine-livereload-task/commit/1acbf12aa02fc33faeb223b87c156fb5f2f96f1e#diff-168726dbe96b3ce427e7fedce31bb0bcR14 but then introduced a regression in https://github.com/mucsi96/gulp-jasmine-livereload-task/commit/8bc658e7df69ba515e7181f6cbddcd6f878001e5#diff-168726dbe96b3ce427e7fedce31bb0bcR19? I will keep looking at this…

**Comment by mucsi96** [comment]
Fix is released in `0.11.0` 🎉 
Can you try it?
Thank you for contribution!

**Comment by glebec** [comment]
Works! 👍
